### ISSUE TITLE
Ajout snow

### ISSUE THREAD

**Issue by RedAXELight** [RedAXELight/I151_BASEIA#1]
Je ne sais pas si le modele reçoit les données du formulaire d'ajout mais la requête SQL ne s'effectue pas

**Comment by NicolasGlassey** [comment]
En utilisant le debugger.

Mettez des points d'arrêt:
*l'index, là où l'action attendue doit être traitée (addSnow...)
*dito dans le contrôleur
*dito dans le modèle

Ainsi vous allez pouvoir identifier là où votre code ne se comporte pas comme attendu.
